# Generated by Django 3.1.3 on 2021-03-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match_results',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('a1', models.CharField(blank=True, db_column='a1', max_length=32, null=True)),
                ('a2', models.CharField(blank=True, db_column='a2', max_length=32, null=True)),
                ('b1', models.CharField(blank=True, db_column='b1', max_length=32, null=True)),
                ('b2', models.CharField(blank=True, db_column='b2', max_length=32, null=True)),
                ('zongbifen', models.CharField(blank=True, db_column='zongbifen', max_length=32, null=True)),
                ('meijubifen', models.CharField(blank=True, db_column='meijubifen', max_length=128, null=True)),
                ('shengli1', models.CharField(blank=True, db_column='shengli1', max_length=32, null=True)),
                ('shengli2', models.CharField(blank=True, db_column='shengli2', max_length=32, null=True)),
            ],
            options={
                'db_table': 'match_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='train_user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, db_column='nickname', max_length=32, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=32, null=True)),
                ('power', models.CharField(blank=True, db_column='power', max_length=32, null=True)),
                ('jifen', models.IntegerField(blank=True, db_column='jifen', null=True)),
            ],
            options={
                'db_table': 'train_user',
                'managed': True,
            },
        ),
    ]
