# Generated by Django 3.1.3 on 2021-03-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_user',
            name='zzjg',
            field=models.CharField(blank=True, db_column='zzjg', max_length=64, null=True),
        ),
    ]
