# Generated by Django 3.1.3 on 2021-03-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_match_results_zzjg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_results',
            name='zzjg',
        ),
        migrations.AddField(
            model_name='match_results',
            name='project',
            field=models.CharField(blank=True, db_column='project', max_length=64, null=True),
        ),
    ]
